version: 2
models:  
  - name: tbl_datamart_monthly_premiums
    description: "A datamart dbt model"
    columns:
      - name: month
        description: "The month associated with the transaction"
      - name: party
        description: "Insurance partner/reinsurer associated with the transaction"
      - name: premium
        description: "Premium value recorded for the transaction"
