version: 2

models:
  - name: tbl_stg_transactions
    description: "Staging model for transactions"
    config:
     tags:
      - staging
    columns:
      - name: customer_id
        description: "{{doc('customer_id')}}"
        tests:
          - not_null
          - unique
      - name: signup_date
        description: "Timestamp when the transaction was created"
        tests:
          - not_null
      - name: created_at
        description: "Timestamp when the transaction was created"
        tests:
              - not_null    
              - unique
              - relationships:
                  to: ref('time_spine')
                  field: date_day
              

