version: 2

models:
  - name: tbl_stg_sensor_readings

    columns:
      - name: device_id
        tests:
          - not_null

      - name: timestamp
        tests:
          - not_null

      - name: soil_moisture_vwc
        tests:
          - not_null

      - name: soil_temp_c
        tests:
          - not_null

      - name: ec_us_cm
        tests:
          - not_null

      - name: light_par
        tests:
          - not_null

      - name: air_humidity_pct
        tests:
          - not_null