version: 2

sources:
  - name: getsafe
    database: my-project-smava
    schema: smava_demo_dataset
    tables:
      - name: customers
        description: "Customer data from Getsafe"
        columns:
          - name: customer_id
            description: "Unique identifier for each customer"
            tests:
              - not_null
              - unique
