
version: 2

models:  
  - name: tbl_fct_premium_transactions
    description: "A metric dbt model"
    columns:
      - name: transaction_id
        description: "Unique identifier for each transaction"
        data_tests:
          - unique
          - not_null
      - name: created_at
        description: "Date and time when the transaction was created."
      - name: premium_month
        description: "The month associated with the transaction. date_trunc('month', created_at) converts every transaction date to the first day of its month (e.g., 2025-06-15 → 2025-06-01). This enables monthly aggregation"
      - name: party
        description: "Insurance partner/reinsurer associated with the transaction"
      - name: premium_amount
        description: "Premium value recorded for the transaction"
      - name: status
        description: "Processing status of the transaction"